using Spectre.Console;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;

namespace Brigit.CLI.Commands;

public static class Scaffolder
{
    public static async Task RunAsync()
    {
        var projectName = AnsiConsole.Ask<string>("Your Project Name? [/]");

        var editor = AnsiConsole.Prompt(
            new SelectionPrompt<string>()
                .Title("Which editor do you use?")
                .AddChoices(new[] { "Visual Studio", "Visual Studio Code" }));

        var ymm4Path = AnsiConsole.Ask<string>("YMM4 Installation Path? [/]");
        if (ymm4Path.EndsWith("\\")) ymm4Path = ymm4Path.TrimEnd('\\');
        
        var plugins = new List<string> { "AviUtl", "AviUtl2", "YMM4" };
        
        await AnsiConsole.Status()
            .Spinner(Spinner.Known.Dots)
            .StartAsync("Creating...", async ctx =>
            {
                GenerateProject(projectName, editor, plugins, ymm4Path);
            });

        AnsiConsole.MarkupLine($"✨Created **{projectName}**! ✨");
        AnsiConsole.MarkupLine($"You can change to your development environment with the following command: [green]cd ./{projectName}[/]");
        AnsiConsole.MarkupLine($"Then run [blue]brigit template[/] to add features.");
    }

    public static async Task AddTemplateAsync()
    {
        
        var templateType = AnsiConsole.Prompt(
            new SelectionPrompt<string>()
                .Title("Which template would you like to add?")
                .AddChoices(new[] { "Effect", "Custom Object", "Transition", "Window", "All Samples" }));

        await AnsiConsole.Status()
            .Spinner(Spinner.Known.Dots)
            .StartAsync("Generating template...", async ctx =>
            {
                GenerateTemplate(templateType);
            });
            
        AnsiConsole.MarkupLine($"[green]Added {templateType} template![/]");
    }

    public static void GenerateProject(string projectName, string editor, List<string> plugins, string ymm4Path)
    {
        var targetDir = Path.Combine(Directory.GetCurrentDirectory(), projectName);
        if (!Directory.Exists(targetDir))
        {
             Directory.CreateDirectory(targetDir);
        }

        File.WriteAllText(Path.Combine(targetDir, "LICENSE"), "MIT License\n\nCopyright (c) 2025 " + Environment.UserName);
        
        File.WriteAllText(Path.Combine(targetDir, "Directory.Build.props"), $@"<Project>
  <PropertyGroup>
    <YMM4DirPath>{ymm4Path}\</YMM4DirPath>
  </PropertyGroup>
</Project>");

        File.WriteAllText(Path.Combine(targetDir, ".gitignore"), @"bin/
obj/
.vs/
.vscode/
*.user
*.suo
");

        var readmeContent = $@"# {projectName}
Generated by **Brigit Framework**.

## One Code, All Platforms.
This project compiles to both a **YMM4 Plugin** (Managed) and an **AviUtl Plugin** (Native).

## Development
Run `brigit template` to add sample codes (Effects, Objects, Windows, etc).

## How to Build

### 1. Build for YMM4
```bash
brigit build
```
";
        File.WriteAllText(Path.Combine(targetDir, "README.md"), readmeContent);
        
        if (editor == "Visual Studio Code")
        {
            var vscodeDir = Path.Combine(targetDir, ".vscode");
            Directory.CreateDirectory(vscodeDir);
            File.WriteAllText(Path.Combine(vscodeDir, "settings.json"), @"{ ""dotnet.defaultSolution"": """ + projectName + @".csproj"" }");
        }

        var csprojContent = $@"<Project Sdk=""Microsoft.NET.Sdk"">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <RootNamespace>{projectName}</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include=""YukkuriMovieMaker.Plugin"">
       <HintPath>$(YMM4DirPath)YukkuriMovieMaker.Plugin.dll</HintPath>
       <Private>false</Private> 
    </Reference>
  </ItemGroup>
</Project>";
        File.WriteAllText(Path.Combine(targetDir, $"{projectName}.csproj"), csprojContent);

        File.WriteAllText(Path.Combine(targetDir, "Plugin.cs"), $@"using System;
using YukkuriMovieMaker.Plugin;
using {projectName}.Bridge;

namespace {projectName}
{{
    public class Plugin : IPlugin 
    {{
        public string Name => ""{projectName}"";
        public void Initialize() 
        {{
            VersionChecker.CheckAsync(""1.0.0"", ""user/repo""); 
        }}
    }}
}}");

        var bridgeDir = Path.Combine(targetDir, "Bridge");
        Directory.CreateDirectory(bridgeDir);
        File.WriteAllText(Path.Combine(bridgeDir, "AviUtlBridge.cs"), $@"using System;
using System.Runtime.InteropServices;

namespace {projectName}.Bridge 
{{
    public static class AviUtlBridge 
    {{
        [UnmanagedCallersOnly(EntryPoint = ""func_init"")]
        public static int FuncInit(IntPtr dllHinst) 
        {{
            return 1;
        }}
    }}
}}");

        File.WriteAllText(Path.Combine(bridgeDir, "VersionChecker.cs"), @"using System.Threading.Tasks; 
namespace " + projectName + @".Bridge { 
    public static class VersionChecker { 
        public static async Task CheckAsync(string current, string repo) { } 
    } 
}");

    }

    public static void GenerateTemplate(string type)
    {
        var targetDir = Directory.GetCurrentDirectory();
        var csproj = Directory.GetFiles(targetDir, "*.csproj").FirstOrDefault();
        var projectName = csproj != null ? Path.GetFileNameWithoutExtension(csproj) : "MyProject";

        if (type == "Effect" || type == "All Samples")
        {
            var effectsDir = Path.Combine(targetDir, "Effects");
            Directory.CreateDirectory(effectsDir);
            File.WriteAllText(Path.Combine(effectsDir, "SampleVideoEffect.cs"), $@"using System.Collections.Generic;
using System.Linq;
using YukkuriMovieMaker.Plugin.Effects;
using YukkuriMovieMaker.Plugin.Effects.Animations;

namespace {projectName}.Effects
{{
    public class SampleVideoEffect : VideoEffectBase 
    {{
        public override string Label => ""Sample Effect"";
        protected override IEnumerable<IAnimatable> GetAnimatables() => Enumerable.Empty<IAnimatable>();
    }}
}}");
            File.WriteAllText(Path.Combine(effectsDir, "SampleAudioEffect.cs"), $@"using System.Collections.Generic;
using System.Linq;
using YukkuriMovieMaker.Plugin.Effects;
using YukkuriMovieMaker.Plugin.Effects.Animations;

namespace {projectName}.Effects
{{
    public class SampleAudioEffect : AudioEffectBase 
    {{
        public override string Label => ""Sample Audio Effect"";
        protected override IEnumerable<IAnimatable> GetAnimatables() => Enumerable.Empty<IAnimatable>();
    }}
}}");
        }

        if (type == "Custom Object" || type == "All Samples")
        {
             var itemsDir = Path.Combine(targetDir, "Items");
             Directory.CreateDirectory(itemsDir);
             File.WriteAllText(Path.Combine(itemsDir, "SampleShape.cs"), $@"using System.Collections.Generic;
using System.Linq;
using YukkuriMovieMaker.Plugin.Shape;
using YukkuriMovieMaker.Plugin.Shape.Animations;

namespace {projectName}.Items
{{
    public class SampleShape : IShapePlugin
    {{
        public string Name => ""Sample Shape"";
        public IEnumerable<IAnimatable> GetAnimatables() => Enumerable.Empty<IAnimatable>();
    }}
}}");
        }

        if (type == "Transition" || type == "All Samples")
        {
             var transDir = Path.Combine(targetDir, "Transitions");
             Directory.CreateDirectory(transDir);
             File.WriteAllText(Path.Combine(transDir, "SampleTransition.cs"), $@"using System.Collections.Generic;
using System.Linq;
using YukkuriMovieMaker.Plugin.Transitions;
using YukkuriMovieMaker.Plugin.Transitions.Animations;

namespace {projectName}.Transitions
{{
    public class SampleTransition : TransitionBase
    {{
         public override string Label => ""Sample Transition"";
         protected override IEnumerable<IAnimatable> GetAnimatables() => Enumerable.Empty<IAnimatable>();
    }}
}}");
        }

        if (type == "Window" || type == "All Samples")
        {
             var winDir = Path.Combine(targetDir, "Windows");
             Directory.CreateDirectory(winDir);
             
             File.WriteAllText(Path.Combine(winDir, "SampleWindow.xaml"), @"<UserControl x:Class=""" + projectName + @".Windows.SampleWindow""
             xmlns=""http://schemas.microsoft.com/winfx/2006/xaml/presentation""
             xmlns:x=""http://schemas.microsoft.com/winfx/2006/xaml""
             mc:Ignorable=""d"" 
             xmlns:d=""http://schemas.microsoft.com/expression/blend/2008"" 
             xmlns:mc=""http://schemas.openxmlformats.org/markup-compatibility/2006"" 
             d:DesignHeight=""300"" d:DesignWidth=""300""
             AllowDrop=""True""
             Background=""#2D2D30"">
    <Grid>
        <TextBlock Text=""Drag &amp; Drop Images Here"" 
                   HorizontalAlignment=""Center"" 
                   VerticalAlignment=""Center"" 
                   Foreground=""White""/>
    </Grid>
</UserControl>");

             File.WriteAllText(Path.Combine(winDir, "SampleWindow.xaml.cs"), $@"using System.Windows;
using System.Windows.Controls;
using System.Linq;

namespace {projectName}.Windows
{{
    public partial class SampleWindow : UserControl
    {{
        public SampleWindow()
        {{
            InitializeComponent();
            this.Drop += OnDrop;
        }}

        private void OnDrop(object sender, DragEventArgs e)
        {{
            if (e.Data.GetDataPresent(DataFormats.FileDrop))
            {{
                string[] files = (string[])e.Data.GetData(DataFormats.FileDrop);
                var images = files.Where(f => f.EndsWith("".png"") || f.EndsWith("".jpg""));
                MessageBox.Show($""Dropped {{images.Count()}} images"");
            }}
        }}
    }}
}}");

             File.WriteAllText(Path.Combine(winDir, "SampleToolPlugin.cs"), $@"using YukkuriMovieMaker.Plugin;
using System.Windows;

namespace {projectName}.Windows
{{
    public class SampleToolPlugin : IToolPlugin
    {{
        public string Name => ""Brigit Tool Window"";

        public IDockableWindow CreateDockableWindow()
        {{
            return new MyDockableWindow();
        }}
    }}

    public class MyDockableWindow : IDockableWindow
    {{
        public string Title => ""Brigit Window"";
        public object Content => new SampleWindow();
    }}
}}");
        }
    }
}
